name: social-media-monorepo-dev
services:
  mongodb:
    image: mongo:8.0
    container_name: sm-mongodb-container
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  auth-api:
    container_name: sm-auth-api-container
    build:
      context: .
      dockerfile: apps/auth-api/Dockerfile
      target: development
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - USERS_API_URL=${USERS_API_URL}
    ports:
      - '3000:3000'
    volumes:
      - ./apps/auth-api:/usr/src/app/apps/auth-api:delegated
      - ./libs:/usr/src/app/libs:delegated
      - ./package.json:/usr/src/app/package.json:delegated
      - ./nx.json:/usr/src/app/nx.json:delegated
      - ./tsconfig.base.json:/usr/src/app/tsconfig.base.json:delegated
      - auth_api_node_modules:/usr/src/app/node_modules
    depends_on:
      - mongodb

  posts-api:
    container_name: sm-posts-api-container
    build:
      context: .
      dockerfile: apps/posts-api/Dockerfile
      target: development
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
    ports:
      - '3001:3000'
    volumes:
      - ./apps/posts-api:/usr/src/app/apps/posts-api:delegated
      - ./libs:/usr/src/app/libs:delegated
      - ./package.json:/usr/src/app/package.json:delegated
      - ./nx.json:/usr/src/app/nx.json:delegated
      - ./tsconfig.base.json:/usr/src/app/tsconfig.base.json:delegated
      - posts_api_node_modules:/usr/src/app/node_modules
    depends_on:
      - mongodb

  users-api:
    container_name: sm-users-api-container
    build:
      context: .
      dockerfile: apps/users-api/Dockerfile
      target: development
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
    ports:
      - '3002:3000'
    volumes:
      - ./apps/users-api:/usr/src/app/apps/users-api:delegated
      - ./libs:/usr/src/app/libs:delegated
      - ./package.json:/usr/src/app/package.json:delegated
      - ./nx.json:/usr/src/app/nx.json:delegated
      - ./tsconfig.base.json:/usr/src/app/tsconfig.base.json:delegated
      - users_api_node_modules:/usr/src/app/node_modules
    depends_on:
      - mongodb

  web-app:
    container_name: sm-web-app-container
    build:
      context: .
      dockerfile: apps/web-app/Dockerfile
      target: development
      args:
        - VITE_AUTH_API_URL=${VITE_AUTH_API_URL}
        - VITE_USERS_API_URL=${VITE_USERS_API_URL}
    ports:
      - '5173:5173'
    volumes:
      - ./apps/web-app:/usr/src/app/apps/web-app:delegated
      - ./libs:/usr/src/app/libs:delegated
      - ./package.json:/usr/src/app/package.json:delegated
      - ./nx.json:/usr/src/app/nx.json:delegated
      - ./tsconfig.base.json:/usr/src/app/tsconfig.base.json:delegated
      - web_app_node_modules:/usr/src/app/node_modules

volumes:
  auth_api_node_modules:
  posts_api_node_modules:
  users_api_node_modules:
  web_app_node_modules:
  mongo_data:
