apiVersion: v1
kind: Secret
metadata:
  name: social-media-monorepo-secrets
  namespace: social-media-monorepo
type: Opaque
stringData:
  MONGO_INITDB_DATABASE: 'social-media-monorepo-db'
  JWT_SECRET: 'SUPER_SECRET_KEY'
  MONGO_URI: 'mongodb://mongo-db-service.social-media-monorepo.svc.cluster.local:27017/social-media-monorepo-db'
