apiVersion: v1
kind: Secret
metadata:
  name: social-media-monorepo-secrets
  namespace: social-media-monorepo
type: Opaque
stringData:
  JWT_SECRET: 'SUPER_SECRET_KEY'
  MONGO_INITDB_DATABASE: 'social-media-monorepo-db'
