apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-api-deployment
  namespace: social-media-monorepo
  labels:
    app: posts-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-api
  template:
    metadata:
      labels:
        app: posts-api
    spec:
      containers:
        - name: posts-api-container
          image: prathoreme/social-media-monorepo-posts-api:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: social-media-monorepo-secrets
            - configMapRef:
                name: social-media-monorepo-configmap
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
