# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: posts-api-hpa
#   namespace: social-media-monorepo
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: posts-api-deployment
#   minReplicas: 1
#   maxReplicas: 2
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70
