apiVersion: v1
kind: Service
metadata:
  name: posts-api-service
  labels:
    app: posts-api
spec:
  selector:
    app: posts-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer