apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
  namespace: social-media-monorepo
spec:
  selector:
    app: mongo-db
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
